### ISSUE TITLE
Terminal Colors

### ISSUE THREAD

**Issue by frere-jacques** [francma/everforest-jetbrains#5]
Font Colors in terminal don't fit theme.
Using dark medium, the font in terminal is still dark.

This is true for all kind of terminals. Terminal, python, run, test etc.

**Comment by frere-jacques** [comment]
I figured out that it's the standard config under 
settings -> Editor -> Color Schemes -> Console Color
That are messed up. Especially Console -> Standard output. Untick mackes it nicer.

No clue how to edit that in this theme.

**Comment by frere-jacques** [comment]
#7 I created this two commits for terminal colors. I am not hundred percent sure whether it would be better to have bright<color> and <color> identical but with background and foreground from background and foreground palettes. Maybe thats more like terminal theme then. If thats the case I can update it.

**Comment by frere-jacques** [comment]
I figured out that the other handling is in fact more desirable and updated the colors accordingly. Please have a look at #8.

**Comment by francma** [comment]
Closed in https://github.com/francma/everforest-jetbrains/pull/8
